[project]
name = "GECS Session 4 - Testing"
description = "A tutorial on code testing with pytest."
version = "0.1.0"
channels = ['conda-forge']
platforms = ['linux-64', 'osx-64', 'osx-arm64', 'win-64']

[dependencies]
python = "~=3.10.0"
ipython = "*"
jupyterlab = "*"
loguru = "*"
matplotlib = "*"
notebook = "*"
numpy = "*"
pandas = "*"
ruff = "*"
tqdm = "*"
typer = "*"
pip = "*"
pytest = "*"
pytest-cov = "*"
pytest-mock = ">=3.15.1,<4"
debugpy = ">=1.8.17,<2"

[pypi-dependencies]
python-dotenv = "*"
src = { path = ".", editable = true }


[tasks]
dataset = "python src/dataset.py main"
analysis = {cmd = "python src/analysis.py main", depends-on = ["dataset"]}
plots = {cmd = "python src/plots.py main", depends-on = ["analysis"]}
all = [{task = "dataset"}, {task = "analysis"}, {task = "plots"}]
clean = "rm -f data/processed/* analyzed/* results/*"
test = "pytest --cov"
