
#!/usr/bin/env python
"""
plot_counts.py
----------------
Plots a histogram of word frequencies from a CSV file generated by count_words.py using matplotlib.
Usage:
    python plot_counts.py <input-file> <output-file> [limit]
"""


import sys

import matplotlib.pyplot as plt
import pandas as pd

from src.plots import plot_word_counts


def main():
    """
    Main entry point for the script. Plots a histogram of word frequencies from a CSV file generated by count_words.py using matplotlib.
    Usage:
        python plot_counts.py <input-file> <output-file> [limit]
    """
    if len(sys.argv) < 3:
        print("Usage: python plot_counts.py <input-file> <output-file> [limit]")
        sys.exit(1)
    input_file = sys.argv[1]
    output_file = sys.argv[2]
    limit = int(sys.argv[3]) if len(sys.argv) > 3 else 10
    df = pd.read_csv(input_file)
    plot_word_counts(df, limit)
    if output_file == "show":
        plt.show()
    else:
        plt.savefig(output_file)

if __name__ == "__main__":
    main()
